# Azure App Service deployment configuration for Python
# This file is used to configure the deployment of the FastAPI backend

[build]
  # Command to install dependencies
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.11"

[run]
  # Command to start the application
  command = "uvicorn main:app --host 0.0.0.0 --port $PORT"
